a.out: Fecha.o Cuac.o Par.o TablaHash.o Nodo.o Arbol.o DiccionarioCuacs.o Cuacker.o
	g++ -g Fecha.o Cuac.o Par.o TablaHash.o Nodo.o Arbol.o DiccionarioCuacs.o Cuacker.o

Fecha.o: Fecha.cpp Fecha.hpp
	g++ -c -g Fecha.cpp

Cuac.o: Cuac.cpp Cuac.hpp
	g++ -c -g Cuac.cpp

Par.o: Par.cpp Par.hpp
	g++ -c -g Par.cpp

TablaHash.o: TablaHash.cpp TablaHash.hpp
	g++ -c -g TablaHash.cpp

Nodo.o: Nodo.cpp Nodo.hpp
	g++ -c -g Nodo.cpp

Arbol.o: Arbol.cpp Arbol.hpp
	g++ -c -g Arbol.cpp

DiccionarioCuacs.o: DiccionarioCuacs.cpp DiccionarioCuacs.hpp
	g++ -c -g DiccionarioCuacs.cpp

Cuacker.o: Cuacker.cpp
	g++ -c -g Cuacker.cpp